server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://db.pauhbpfnpelchbkawjhh.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  supabase:
    url: ${SUPABASE_URL}
    key: ${SUPABASE_KEY}
    anon-key: ${SUPABASE_ANON_KEY}
    service-key: ${SUPABASE_SERVICE_KEY}

  groq:
    api-key: ${GROQ_API_KEY}

  pexels:
    api-key: ${PEXELS_API_KEY}

  api:
    url: ${API_URL}