package com.example.demo.service;

import java.util.List;

/**
 * Narrative generated by the second Groq call, once hotel + restaurant
 * results are available. Used only internally by {@code AiTravelPlannerService}.
 */
public record AiTravelPlanNarrativeDto(
        String greeting,
        String summary,
        String assistantMessage,
        List<String> suggestedFollowUps
) {
}